apiVersion: v2
appVersion: "1.0"
description: A chart containing Matomo
name: matomo
version: 0.2.0
home: https://matomo.org/
sources:
  - https://github.com/matomo-org/matomo
  - https://github.com/brunowego/matomo-helm
maintainers:
  - name: nicolaischmid
dependencies:
  - name: mysql
    version: ~1.6.6
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: mysql.enabled
  - name: redis
    version: ~10.2.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: redis.enabled
