apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: matomo
version: 0.1.0
home: https://matomo.org/
sources:
- https://github.com/matomo-org/matomo
- https://github.com/brunowego/matomo-helm
maintainers:
- name: brunowego
  email: brunowego@gmail.com
